# @package _global_
defaults:
  - defaults
  - override hydra/launcher: submitit_slurm
  - _self_

experiment_name: 'sam'
checkpoint_epoch_interval: 5
validation_epoch_interval: 5
data:
  train_dataset_names: ['3doi_v1']
  val_dataset_names: ['3doi_v1']
  test_dataset_names: ['3doi_v1']
  image_size: [768, 1024]
train:
  batch_size: 2
  depth_on: True
test:
  mode: 'export_imgs'
optimizer:
  max_epochs: 200
  name: 'AdamW'
  mixed_precision: 'fp16'
  lr: 1e-4
  lr_backbone: 1e-5
  lr_scheduler_name: 'StepLR'
  lr_scheduler_step_size: 500 # epoch
  lr_scheduler_gamma: 0.1
  lbd_movable: 0.5
  lbd_rigid: 0.5
  lbd_kinematic: 0.5
  lbd_action: 0.5
  lbd_mask: 2.0
  lbd_dice: 1.0
  lbd_affordance: 400.0
  lbd_bbox: 5.0
  lbd_giou: 2.0
  lbd_axis: 2.0
  lbd_axis_offset: 10.0
  lbd_eascore: 0.0
  lbd_depth: 1.0
  clip_max_norm: 0.1
model:
  name: "sam"
  backbone_name: "vit_b"
hydra:
  launcher:
    name: 'SAM'
    timeout_min: 8640
    cpus_per_task: 4
    gpus_per_node: 4
    tasks_per_node: 4
    mem_per_cpu: 12000
    account: 'fouhey2'
    nodes: 1
    partition: 'spgpu'
    exclude: 'gl1522'
